// Autogenerated by Dirpcgen (2.4.6)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package idl

import (
	"fmt"
)

// Attributes:
//  - CityId
//  - Version
//  - Keyword
//  - Uid
//  - SceneId
//  - FlowId
//  - IsDebug
type RequestInfo struct {
	CityId         int64  `thrift:"city_id,1,required" json:"cityId"`
	Version        string `thrift:"version,2,required" json:"version"`
	Keyword        string `thrift:"keyword,3,required" json:"keyword"`
	Uid            int64  `thrift:"uid,4,required" json:"uid"`
	SceneId        int64  `thrift:"scene_id,5,required" json:"scene_id"`
	FlowId         int64  `thrift:"flow_id,6,required" json:"flow_id"`
	IsDebug        bool   `thrift:"is_debug,7,required" json:"is_debug"`
}

func NewRequestInfo() *RequestInfo {
	return &RequestInfo{}
}

func (r *RequestInfo) New() *RequestInfo {
	return &RequestInfo{}
}

func (p *RequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestInfo(%+v)", *p)
}

// Attributes:
//  - Errno
//  - Errmsg
//  - Data
type ResponseInfo struct {
	Errno  int32     `thrift:"errno,1,required" json:"errno"`
	Errmsg string    `thrift:"errmsg,2,required" json:"errmsg"`
	Data   *DataType `thrift:"data,3,required" json:"data"`
}

func NewResponseInfo() *ResponseInfo {
	return &ResponseInfo{}
}

func (r *ResponseInfo) New() *ResponseInfo {
	return &ResponseInfo{}
}

func (p *ResponseInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResponseInfo(%+v)", *p)
}

// Attributes:
//  - Items
//  - Version
type DataType struct {
	Items          []*ItemType      `thrift:"items,1,required" json:"items"`
	Version        string           `thrift:"version,2,required" json:"version"`
}

func NewDataType() *DataType {
	return &DataType{}
}

func (r *DataType) New() *DataType {
	return &DataType{}
}

func (p *DataType) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DataType(%+v)", *p)
}

// Attributes:
//  - Name
//  - Price
//  - Score
//  - GoodsId
type ItemType struct {
	Name               string  `thrift:"name,1,required" json:"name"`
	Price              float64 `thrift:"price,2,required" json:"price"`
	Score              float64   `thrift:"score,3,required" json:"score"`
	GoodsId            int64   `thrift:"goods_id,4,required" json:"goods_id"`
}

func NewItemType() *ItemType {
	return &ItemType{}
}

func (r *ItemType) New() *ItemType {
	return &ItemType{}
}

func (p *ItemType) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemType(%+v)", *p)
}

